### ISSUE TITLE
Create a PDF

### ISSUE THREAD

**Issue by PragTob** [PragTob/rails-beginner-cheatsheet#2]
It would be awesome to have a really readable and good looking pdf version of this that can be downloaded. For now "printing" it as PDF kind of works but is not really beautiful... 

Some css styling anyone?

**Comment by PragTob** [comment]
@carladrago created a nice looking PDF, as long as there is no repeatable cool process to generate a PDF I will likely add it for the time being as a download.

**Comment by lbain** [comment]
I'd also love it in PDF form! But in the meantime - @PragTob, do you have the link to the PDF you mentioned?

**Comment by PragTob** [comment]
Oh yes I totally do but forgot to upload it.. too less time. On my todo list for tomorrow, if it#s not done in 24h please ping me! :-)

Otherwise you could also "print" the page with a PDF printer.

**Comment by PragTob** [comment]
Hi @lbain thanks to @carladrago we know have [a PDF](http://pragtob.github.io/rails-beginner-cheatsheet/RailsBeginnerCheatSheet.pdf)!

Cheers,
Tobi
