### ISSUE TITLE
Provide installaion help? (especially Rails 4)

### ISSUE THREAD

**Issue by PragTob** [PragTob/rails-beginner-cheatsheet#32]
Maybe links to some installation instructions/tools should be provided. It gets more complicated to set up these environments, as railsinstaller does not seem to make a new release (for 4.0) for either Windows or MacOSX.

I'm not up to date as for what the best installation instructions are for Windows/MacOSX.

And well for Linux for me it's install RVM + deps, then ruby deps, then ruby, git and sqlite package through package manager then and that should be it.

Input very much welcome.

**Comment by DanielKehoe** [comment]
You might consider the articles I maintain:

http://railsapps.github.io/installing-rails.html
http://railsapps.github.io/installrubyonrails-mac.html
http://railsapps.github.io/installrubyonrails-ubuntu.html
http://railsapps.github.io/rubyonrails-nitrous-io.html

**Comment by PragTob** [comment]
Hi thanks @DanielKehoe !

Will have a look at them but I bet they're good. Just this morning I saw that you made a video/guid for installing on OSX Mavericks. Thanks!

Tobi
